### ISSUE TITLE
make simple search suggestions not case sensitive

### ISSUE THREAD

**Issue by cdoorenweerd** [carlosp420/VoSeq#236]
When I search for something with a capital letter (a genus) it gives me the search suggestion to look for the same thing without a capital letter. The results are the same. When I search for the genus with a small letter, it does not give me a suggestion for alternative search. Not a big problem, but it gives the suggestion that I've typed something wrong where I haven't. Hopefully an easy fix :)

**Comment by carlosp420** [comment]
good catch!
