### ISSUE TITLE
simple search code in voseq

### ISSUE THREAD

**Issue by cdoorenweerd** [carlosp420/VoSeq#237]
It would be really nice if not only names could be searched with simple search, but also codes in voseq!

**Comment by carlosp420** [comment]
I does simple search by code. Check this out:

![a](https://cloud.githubusercontent.com/assets/710117/8324431/27ae8a9a-1a59-11e5-8a3d-256341e95077.png)

I added "code" to the place-holder so it is obvious:

![b](https://cloud.githubusercontent.com/assets/710117/8324441/3fdc69b6-1a59-11e5-8acd-8ac7d1849ddd.png)
