### ISSUE TITLE
Warning for strange characters when converting to aa

### ISSUE THREAD

**Issue by niklas-w** [carlosp420/VoSeq#272]
I noticed that VoSeq ignores strange characters, e.g. ~ , when converting to amino acid sequences, which means the sequence becomes shorter and out of sync with the rest. A warning should come up? Or is there a warning already when one tries to import the original sequence?

**Comment by carlosp420** [comment]
maybe better to do the checks and warnings when saving or importing the sequences so the database stays clean.

**Comment by carlosp420** [comment]
fixed by 7d2b1ab22fea14ac17eb5e64eb1eb204644845c0
