### ISSUE TITLE
nothing happens when attempting to create voucher table

### ISSUE THREAD

**Issue by mariespe** [carlosp420/VoSeq#342]
I have made a taxonset and want to create a Voucher table (excel file), but when I press the 'Create dataset' button nothing happens. I also tried to enter the voucher codes manually, but still nothing. 

I have installed Voseq locally on a Macbook Pro running OSX 10.11.5 using the quick and easy install.

**Comment by carlosp420** [comment]
You need to select also the gene codes that you want to include in your Excel table. True that a message should be shown if the user attempts to create a voucher table without specifying the genes.

**Comment by carlosp420** [comment]
I just added an alert message when the genes are not specified from the form.
![alert](https://cloud.githubusercontent.com/assets/710117/18806337/67633d1c-81ef-11e6-8e6a-21eddf200cc0.png)
