### ISSUE TITLE
replace "batch update" with "adding batch of info to existing records"

### ISSUE THREAD

**Issue by carlosp420** [carlosp420/VoSeq#4]

**Comment by cdoorenweerd** [comment]
I would prefer "batch update", with a checkbox option to select whether existing data should be overwritten or not. Preferably, before the actual overwrite happens, there should be a list indicating all changes about to happen which the user can verify or still cancel at that moment.

**Comment by carlosp420** [comment]
@cdoorenweerd I just implemented this plugin. It has a confirmation page which show the changes that you are going to make. I think it is not possible yet to check items to confirm certain changes. However it would be possible to abort the import, fix the data file and resume import.

This plugin allows importing XLS, CSV, JSON, YaML files!

![a](https://cloud.githubusercontent.com/assets/710117/8375726/9eb29252-1c08-11e5-993a-99f3e677c479.png)

**Comment by cdoorenweerd** [comment]
Beautiful! I think this is fine, no need to verify each individual change
